"""
schema_drift.ci

Used by GitHub Actions to compare schema between base and head commits,
generate a markdown report, and signal breaking changes.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

from .diff import diff_schemas, has_changes, is_breaking


MARKER = "<!-- schema-drift-report -->"


def _diff_to_markdown(diff: dict) -> str:
    lines: list[str] = []
    breaking: list[str] = []
    safe: list[str] = []

    for table in diff.get("tables_removed", []):
        breaking.append(f"| ❌ table dropped | `{table}` | — |")
    for c in diff.get("columns_removed", []):
        t = c["was"].get("type", "")
        breaking.append(f"| ❌ column dropped | `{c['table']}.{c['column']}` | was `{t}` |")
    for c in diff.get("columns_modified", []):
        before = c["before"].get("type", "")
        after = c["after"].get("type", "")
        breaking.append(f"| ⚠️ column changed | `{c['table']}.{c['column']}` | `{before}` → `{after}` |")
    for table in diff.get("tables_added", []):
        safe.append(f"| ✅ table added | `{table}` | — |")
    for c in diff.get("columns_added", []):
        t = c["definition"].get("type", "")
        safe.append(f"| ✅ column added | `{c['table']}.{c['column']}` | `{t}` |")
    for i in diff.get("indexes_added", []):
        cols = ", ".join(i["definition"].get("columns", []))
        safe.append(f"| ✅ index added | `{i['index']}` on `{i['table']}` | `{cols}` |")
    for i in diff.get("indexes_removed", []):
        breaking.append(f"| ⚠️ index dropped | `{i['index']}` on `{i['table']}` | — |")

    if not breaking and not safe:
        return ""

    lines.append(MARKER)
    lines.append("## 🔍 Schema drift detected")
    lines.append("")
    lines.append("| status | object | detail |")
    lines.append("| ------ | ------ | ------ |")
    lines.extend(breaking)
    lines.extend(safe)
    lines.append("")

    if breaking:
        lines.append("> [!CAUTION]")
        lines.append("> **Breaking changes detected.** Dropping tables or columns is destructive and may cause data loss.")
    else:
        lines.append("> [!NOTE]")
        lines.append("> No breaking changes. All modifications are additive.")

    lines.append("")
    lines.append("<sub>Generated by [schema-drift](https://github.com/woxlo1/schema-drift)</sub>")
    return "\n".join(lines)


def _get_schema_at(ref: str, db_url: str, storage_file: str = ".schema-drift.json") -> dict | None:
    result = subprocess.run(
        ["git", "show", f"{ref}:{storage_file}"],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        try:
            history = json.loads(result.stdout)
            if history:
                return history[-1]["schema"]
        except (json.JSONDecodeError, KeyError):
            pass

    if db_url:
        try:
            from .core import SchemaDrift
            drift = SchemaDrift(db_url)
            return drift._backend.extract()
        except Exception as e:
            print(f"warning: could not extract schema from DB: {e}", file=sys.stderr)
    return None


def _set_output(key: str, value: str) -> None:
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a") as f:
            f.write(f"{key}={value}\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare schema between two git refs.")
    parser.add_argument("--base-ref", required=True)
    parser.add_argument("--head-ref", required=True)
    parser.add_argument("--output-file", default="drift-report.md")
    parser.add_argument("--storage", default=".schema-drift.json")
    args = parser.parse_args()

    db_url = os.environ.get("SCHEMA_DRIFT_DB", "")
    print(f"Comparing schema: {args.base_ref[:8]} → {args.head_ref[:8]}")

    base_schema = _get_schema_at(args.base_ref, db_url, args.storage)
    head_schema = _get_schema_at(args.head_ref, db_url, args.storage)

    if base_schema is None or head_schema is None:
        print("warning: could not retrieve one or both schemas. Skipping diff.")
        _set_output("breaking", "false")
        return

    diff = diff_schemas(base_schema, head_schema)

    if not has_changes(diff):
        print("No schema changes detected.")
        _set_output("breaking", "false")
        Path(args.output_file).write_text("")
        return

    report = _diff_to_markdown(diff)
    Path(args.output_file).write_text(report)
    print(f"Report written to {args.output_file}")

    _set_output("breaking", "true" if is_breaking(diff) else "false")

    if is_breaking(diff):
        print("Breaking changes detected!")
        sys.exit(1)
    else:
        print("No breaking changes.")


if __name__ == "__main__":
    main()
